Enhance: enh::time_stamp Class Reference
enh::time_stamp Class Reference
Class for time manipulation.
#include <time_stamp.enh.h>
Public Member Functions
constexpr void setTime (unsigned short sec, unsigned short min, unsigned short hr)
Sets the time to the time indicated by arguments.
void setTime (time_t timeStamp)
Sets the time to the time indicated by argument.
void setTime ()
Sets the time to the current time.
constexpr time_stamp (unsigned short sec, unsigned short min, unsigned short hr)
Sets the time to the time indicated by arguments.
time_stamp (time_t timeStamp)
Sets the time to the time indicated by argument.
time_stamp ()
Sets the time to the current time.
constexpr unsigned long long addHours (unsigned long long hr) noexcept
Adds to the hour part of time held.
constexpr unsigned long long addMinutes (unsigned long long min) noexcept
Adds to the minute part of time held (also hour).
constexpr unsigned long long addSeconds (unsigned long long sec) noexcept
Adds to the second part of time held (also hour).
constexpr unsigned long long subHours (unsigned long long hr) noexcept
Reduce the hour part of time held.
constexpr unsigned long long subMinutes (unsigned long long min) noexcept
Reduce the minute part of time held (also hour).
constexpr unsigned long long subSeconds (unsigned long long sec) noexcept
Reduces the second part of time held (also hour).
constexpr unsigned short getSeconds () const noexcept
Get Seconds field.
constexpr unsigned short getMinutes () const noexcept
Get Minutes field.
constexpr unsigned short getHours () const noexcept
Get Hours field.
std::string getStringTime () const
Get The time as a string in default format.
std::string getStringTime (std::string format) const
Get The time as a string in custom format.
constexpr bool isEqualTo (const time_stamp &dt) const noexcept
Checks if argument is equal to this object.
constexpr bool isNotEqualTo (const time_stamp &dt) const noexcept
Checks if argument is not equal to this object.
constexpr bool isLesserThan (const time_stamp &dt) const noexcept
Checks if current time_stamp is lesser than argument.
constexpr bool isLesserThanEq (const time_stamp &dt) const noexcept
Checks if current time_stamp is lesser than or equal to argument.
constexpr bool isGreaterThan (const time_stamp &dt) const noexcept
Checks if current time_stamp is greater than argument.
constexpr bool isGreaterThanEq (const time_stamp &dt) const noexcept
Checks if current time_stamp is greater than or equal to argument.
Detailed Description
Class for time manipulation.
Examples
 #include <time_stamp.enh.h>
 #include <iostream>
 int main()
 {
     enh::time_stamp time_array[] = { {}, {std::time(nullptr)}, {25,36,12} };
     time_array[1].addHours(230);
     time_array[1].addHours(230);
     for (auto i : time_array)
     {
         std::cout << i.getHours() << " " << i.getMinutes() << " " << i.getSeconds() << "\n\n";
         std::cout << "def : " << i.getStringTime() << "\n";
         std::string form[] = {
             "sec, min, hour",
             "secs min minutes, hour hours",
             "hour : min / 60 : sec / 3600",
             "hour/min/sec",
             "houro min' sec''"
         };
         for (auto j : form)
         {
             std::cout << "format : " << j << " >>  " << i.getStringTime(j) << "\n";
         }
         std::cout << "\n";
     }
     return 0;
 }
 /* ****************************************************************************
 Output :
 17 3 38
 def : 17 : 03 : 38
 format : sec, min, hour >>  38, 03, 17
 format : secs min minutes, hour hours >>  38s 03 minutes, 17 hours
 format : hour : min / 60 : sec / 3600 >>  17 : 03 / 60 : 38 / 3600
 format : hour/min/sec >>  17/03/38
 format : houro min' sec'' >>  17o 03' 38''
 17 3 38
 def : 17 : 03 : 38
 format : sec, min, hour >>  38, 03, 17
 format : secs min minutes, hour hours >>  38s 03 minutes, 17 hours
 format : hour : min / 60 : sec / 3600 >>  17 : 03 / 60 : 38 / 3600
 format : hour/min/sec >>  17/03/38
 format : houro min' sec'' >>  17o 03' 38''
 12 36 25
 def : 12 : 36 : 25
 format : sec, min, hour >>  25, 36, 12
 format : secs min minutes, hour hours >>  25s 36 minutes, 12 hours
 format : hour : min / 60 : sec / 3600 >>  12 : 36 / 60 : 25 / 3600
 format : hour/min/sec >>  12/36/25
 format : houro min' sec'' >>  12o 36' 25''
 ******************************************************************************/
Constructor & Destructor Documentation
time_stamp() [1/2]
constexpr enh::time_stamp::time_stamp (unsigned short sec, unsigned short min, unsigned short hr) inline constexpr
Sets the time to the time indicated by arguments.
Exception
Throws std::invalid_argument if sec, min, hr is not within bounds. [0,60], [0,59], [0,23] respectively.
Parameters
sec : in : The seconds field [0,60].
min : in : The minutes field [0,59].
hr : in : The hours field [0,59].
time_stamp() [2/2]
enh::time_stamp::time_stamp (time_t timeStamp) inline
Sets the time to the time indicated by argument.
Parameters
timeStamp : in : The time to set.
References setTime().
Member Function Documentation
addHours()
constexpr unsigned long long enh::time_stamp::addHours (unsigned long long hr) inline constexpr noexcept
Adds to the hour part of time held.
Return
Returns the number of days passed (hr/24).
Parameters
hr : in : The hours to add.
addMinutes()
constexpr unsigned long long enh::time_stamp::addMinutes (unsigned long long min) inline constexpr noexcept
Adds to the minute part of time held (also hour).
Return
Returns the number of days passed (min/(24*60)).
Parameters
min : in : The minutes to add.
References addHours(), and enh::min().
addSeconds()
constexpr unsigned long long enh::time_stamp::addSeconds (unsigned long long sec) inline constexpr noexcept
Adds to the second part of time held (also hour).
Return
Returns the number of days passed (sec/(24*60*60)).
Parameters
sec : in : The seconds to add.
References addMinutes().
getStringTime() [1/2]
std::string enh::time_stamp::getStringTime () const inline
Get The time as a string in default format.
hour:min:sec
Overload
inline std::string getStringTime(std::string format) const;
References enh::signExtendValue().
getStringTime() [2/2]
std::string enh::time_stamp::getStringTime (std::string format) const inline
Get The time as a string in custom format.
Pass Argument as a string containing any of the following components.
sec : The seconds.
min : The minutes.
hour : The hours.
Example : "secs minm hourhr" : "25s 25m 10hr"
Overload
inline std::string getStringTime() const;
Parameters
format : in : The format of date.
References enh::signExtendValue().
isEqualTo()
constexpr bool enh::time_stamp::isEqualTo (const time_stamp & dt) const inline constexpr noexcept
Checks if argument is equal to this object.
Return
Returns true if hours, minutes and seconds of argument is equal to current object.
Parameters
dt : in : The time_stamp to compare with.
isGreaterThan()
constexpr bool enh::time_stamp::isGreaterThan (const time_stamp & dt) const inline constexpr noexcept
Checks if current time_stamp is greater than argument.
Return
Returns true if current time_stamp is greater than argument.
Parameters
dt : in : The time_stamp to compare with.
References isLesserThanEq().
isGreaterThanEq()
constexpr bool enh::time_stamp::isGreaterThanEq (const time_stamp & dt) const inline constexpr noexcept
Checks if current time_stamp is greater than or equal to argument.
Return
Returns true if current time_stamp is greater than or equal to argument.
Parameters
dt : in : The time_stamp to compare with.
References isLesserThan().
isLesserThan()
constexpr bool enh::time_stamp::isLesserThan (const time_stamp & dt) const inline constexpr noexcept
Checks if current time_stamp is lesser than argument.
Return
Returns true if current time_stamp is lesser than argument.
Parameters
dt : in : The time_stamp to compare with.
isLesserThanEq()
constexpr bool enh::time_stamp::isLesserThanEq (const time_stamp & dt) const inline constexpr noexcept
Checks if current time_stamp is lesser than or equal to argument.
Return
Returns true if current time_stamp is lesser than or equal to argument.
Parameters
dt : in : The time_stamp to compare with.
isNotEqualTo()
constexpr bool enh::time_stamp::isNotEqualTo (const time_stamp & dt) const inline constexpr noexcept
Checks if argument is not equal to this object.
Return
Returns true if hours, minutes and seconds of argument is not equal to current object.
Parameters
dt : in : The time_stamp to compare with.
References isEqualTo().
setTime() [1/2]
void enh::time_stamp::setTime (time_t timeStamp) inline
Sets the time to the time indicated by argument.
Parameters
timeStamp : in : The time to set.
References enh::localtime(), and setTime().
setTime() [2/2]
constexpr void enh::time_stamp::setTime (unsigned short sec, unsigned short min, unsigned short hr) inline constexpr
Sets the time to the time indicated by arguments.
Exception
Throws std::invalid_argument if sec, min, hr is not within bounds. [0,60], [0,59], [0,23] respectively.
Parameters
sec : in : The seconds field [0,59].
min : in : The minutes field [0,59].
hr : in : The hours field [0,59].
References enh::min().
subHours()
constexpr unsigned long long enh::time_stamp::subHours (unsigned long long hr) inline constexpr noexcept
Reduce the hour part of time held.
Return
Returns the number of days reduced (hr/24).
Parameters
hr : in : The hours to reduce.
subMinutes()
constexpr unsigned long long enh::time_stamp::subMinutes (unsigned long long min) inline constexpr noexcept
Reduce the minute part of time held (also hour).
Return
Returns the number of days passed (min/(24*60)).
Parameters
min : in : The minutes to reduce.
References enh::min(), and subHours().
subSeconds()
constexpr unsigned long long enh::time_stamp::subSeconds (unsigned long long sec) inline constexpr noexcept
Reduces the second part of time held (also hour).
Return
Returns the number of days passed (sec/(24*60*60)).
Parameters
sec : in : The seconds to reduce.
References subMinutes().
The documentation for this class was generated from the following file:
F:/source/Enhance/src/Header/time_stamp.enh.h