Enhance: enh::error_base< type > Class Template Reference
enh::error_base< type > Class Template Reference
The class for inheriting error tracking Functionality.
#include <error_base.enh.h>
Public Types
using error = type
The alias to hold constants for error reporting.
Public Member Functions
error_base ()
default constructor, constructs it as SAFE no error.
void clear () noexcept
The function to clear error flag.
error getError () const noexcept
The function to get error flag.
bool checkFlag (error check_flag) const noexcept
The function to check if certian error(s) are present.
bool isSafe () const noexcept
The function to check if no error flag(s) are set.
void Log (std::string file, std::string function, unsigned long line, std::string variable) const noexcept
Logs value of flag at calling line, function and file to a file indicated by current thread.
Static Public Attributes
static constexpr error SAFE = 0x00
0x00 : No error after last clear.
static constexpr error UNKNOWN = 0x01
0x01 : Unknown Error.
static constexpr error INVALID_ARG = 0x02
0x02 : Invalid argument.
Protected Member Functions
tristate setFlag (error set) noexcept
The function to add the error given as argument to the error flag of class.
tristate clearFlag (error bitClear) noexcept
The function to clear certian fields from error set.
Protected Attributes
std::atomic< error > flag
The error if any occured.
Detailed Description
template<class type>
class enh::error_base< type >
The class for inheriting error tracking Functionality.
hasErrorHandlers = false;
Value 0x00 is reserved for Safe.
Value 0x01 is reserved for unknown errors.
Value 0x02 is reserved for invalid argument errors.
Template Argument
The underlying type to hold error information. (must be integral).
Example
 #include <error_base.enh.h>
 #include <iostream>
 class derived_type : public enh::error_base<unsigned char>
 {
 public:
     static constexpr error USER_DEF = 0x04;
 #ifdef ERROR_BASE_LOG
 private:
     virtual std::string derived_class() const noexcept
     {
         return "derived_type";
     }
     virtual std::string error_string()  const
     {
         std::string ret = error_base::error_string();
         if (ret == "SAFE")
             return ret;
         if (checkFlag(USER_DEF))
             ret += " + USER_DEF";
         return ret;
     }
 #endif
 public:
     void setFlag__(error fl)
     {
         setFlag(fl);
     }
 };
 int main()
 {
     LOG_LINE;
     derived_type t;
     t.setFlag__(derived_type::INVALID_ARG);
     std::cout << std::boolalpha << t.checkFlag(derived_type::INVALID_ARG);
     ERROR_FLAG_LOG(t);
     t.setFlag__(derived_type::USER_DEF);
     std::cout << std::boolalpha << t.checkFlag(derived_type::USER_DEF);
     ERROR_FLAG_LOG(t);
     return 0;
 }
 /* ****************************************************************************
 Output :
 Log file will not be made if _DEBUG is not set or ENH_CLEAR_OP__ is set or if
 optimisation is more than 1
 Console:
 truetrue
 14720_thread_fn_main.log:
 Thread id : 14720
 thread first logging function main
                 F:\error_base_ex.cpp :     36              main
                 F:\error_base_ex.cpp :     44              main ::   derived_type t flag :  + INVALID_ARG
                 F:\error_base_ex.cpp :     50              main ::   derived_type t flag :  + INVALID_ARG + USER_DEF
 ******************************************************************************/
Member Function Documentation
checkFlag()
template<class type > bool enh::error_base< type >::checkFlag (error check_flag) const inline noexcept
The function to check if certian error(s) are present.
Return
Returns true if passed error exists in tag.
Parameters
check_flag : in : flag to check if raised.
References enh::checkField(), and enh::error_base< type >::flag.
clear()
template<class type > void enh::error_base< type >::clear () inline noexcept
The function to clear error flag.
References enh::error_base< type >::flag, and enh::error_base< type >::SAFE.
clearFlag()
template<class type > tristate enh::error_base< type >::clearFlag (error bitClear) inline protected noexcept
The function to clear certian fields from error set.
For clearing certian flags after it has been resolved.
Return
Returns value tristate::ERROR if flag is not set, tristate::GOOD else.
Parameters
bitClear : in : flag to be removed.
References enh::checkField(), enh::ERROR, enh::error_base< type >::flag, and enh::GOOD.
getError()
template<class type > error enh::error_base< type >::getError () const inline noexcept
The function to get error flag.
Return
The error flag.
References enh::error_base< type >::flag.
isSafe()
template<class type > bool enh::error_base< type >::isSafe () const inline noexcept
The function to check if no error flag(s) are set.
Return
true if no error flags are set.
References enh::error_base< type >::flag, and enh::error_base< type >::SAFE.
Log()
template<class type > void enh::error_base< type >::Log (std::string file, std::string function, unsigned long line, std::string variable) const inline noexcept
Logs value of flag at calling line, function and file to a file indicated by current thread.
Parameters
file : in : The file in which logging code is present.
function : in : Logging function name.
line : in : The line of file in which logging code is present.
variable : in : The variable name of error holder.
References debug::Log().
setFlag()
template<class type > tristate enh::error_base< type >::setFlag (error set) inline protected noexcept
The function to add the error given as argument to the error flag of class.
For Setting flag while simultaneously return error state.
Return
Returns value tristate::ERROR.
Parameters
set : in : flag to be added.
References enh::ERROR, and enh::error_base< type >::flag.
The documentation for this class was generated from the following file:
F:/source/Enhance/src/Header/error_base.enh.h