Enhance: enh::date Class Reference
enh::date Class Reference
Class to represent date.
#include <date.enh.h>
Public Member Functions
void add_day ()
Add one day to date.
void setDate (unsigned short dy, unsigned short mnth, long yr, unsigned short week, unsigned ydy)
Sets the date to the date indicated by arguments.
void setDate (time_t timeStamp)
Sets the date to the date indicated by argument.
void setDate ()
Sets the date to the date current date.
date (unsigned short dy, unsigned short mnth, long yr, unsigned short week, unsigned ydy)
Sets the date to the date indicated by arguments.
date (time_t timeStamp)
Sets the date to the date indicated by argument.
date ()
Sets the date to the date current date.
unsigned short getDayOfMonth () const noexcept
The day of this month.
unsigned short getMonth () const noexcept
The number of months after January of this year.
std::string getMonthString () const
The name of the month.
std::string getShortMonthString () const
The name of the month (shortened).
long getYear () const noexcept
The Year.
unsigned short getDayOfWeek () const noexcept
The number of days after last Sunday.
unsigned getDayOfYear () const noexcept
The number of days after 1st of January this year.
std::string getDayOfWeekString () const
The name of the day.
std::string getShortDayOfWeekString () const
The name of the day (shortened).
std::string getDaySuperScript () const
The superscript to be added after the month.
std::string getStringDate () const
Get The date as a string.
std::string getStringDate (std::string format) const
Get The date as a string in custom format.
Detailed Description
Class to represent date.
Example
 #include <date.enh.h>
 #include <iostream>
 int main()
 {
     enh::date dt[] = { {},{std::time(nullptr) + 3600 * 35 * 24}, {21,4,2020,2,75} };
     for (auto i : dt)
     {
         std::cout << i.getDayOfWeek() << " " << i.getDayOfWeekString() << " " << i.getShortDayOfWeekString()
             << " " << i.getDayOfMonth() << i.getDaySuperScript() << " " << i.getMonth() << " " << i.getMonthString()
             << " " << i.getShortMonthString() << " " << i.getDayOfYear() << "\n\n";
         std::cout << "def : " << i.getStringDate() << "\n\n";
         std::string form[] = {
             "shDay, ddth mm yyyy",
             "Day, dd Month yyyy",
             "shDay, ddth shMonth yyyy",
             "dd/mm/yyyy",
             "ddth : Day, Month : yyyy"
         };
         for (auto j : form)
             std::cout << "Format : " << j << " >> " << i.getStringDate(j) << "\n";
     }
     return 0;
 }
 /* ****************************************************************************
 Output :
 3 Wednesday Wed 13th 4 May May 133
 def : Wednesday, 13th May 2020
 Format : shDay, ddth mm yyyy >> Wed, 13th 05 2020
 Format : Day, dd Month yyyy >> Wednesday, 13 May 2020
 Format : shDay, ddth shMonth yyyy >> Wed, 13th May 2020
 Format : dd/mm/yyyy >> 13/05/2020
 Format : ddth : Day, Month : yyyy >> 13th : Wednesday, May : 2020
 3 Wednesday Wed 17th 5 June Jun 168
 def : Wednesday, 17th June 2020
 Format : shDay, ddth mm yyyy >> Wed, 17th 06 2020
 Format : Day, dd Month yyyy >> Wednesday, 17 June 2020
 Format : shDay, ddth shMonth yyyy >> Wed, 17th Jun 2020
 Format : dd/mm/yyyy >> 17/06/2020
 Format : ddth : Day, Month : yyyy >> 17th : Wednesday, June : 2020
 2 Tuesday Tue 21st 4 May May 75
 def : Tuesday, 21st May 2020
 Format : shDay, ddth mm yyyy >> Tue, 21st 05 2020
 Format : Day, dd Month yyyy >> Tuesday, 21 May 2020
 Format : shDay, ddth shMonth yyyy >> Tue, 21st May 2020
 Format : dd/mm/yyyy >> 21/05/2020
 Format : ddth : Day, Month : yyyy >> 21st : Tuesday, May : 2020
 ******************************************************************************/
Constructor & Destructor Documentation
date() [1/2]
enh::date::date (unsigned short dy, unsigned short mnth, long yr, unsigned short week, unsigned ydy) inline
Sets the date to the date indicated by arguments.
Exception
Throws std::invalid_argument if dy, mnth, week, ydy is not within bounds. [0,month_limit], [0,11], [0,6], [0,year_limit) respectively.
Parameters
dy : in : The day of the month [1,month_limit].
mnth : in : The number of months after January [0,11].
yr : in : The Year.
week : in : The day of the week after Sunday [0,6].
ydy : in : The number of day after 01 January of that year [1,year_limit).
References setDate().
date() [2/2]
enh::date::date (time_t timeStamp) inline
Sets the date to the date indicated by argument.
Parameters
timeStamp : in : The time stamp which contains the date.
References setDate().
Member Function Documentation
getDaySuperScript()
std::string enh::date::getDaySuperScript () const inline
The superscript to be added after the month.
eg st : 21st, rd : 23rd, nd : 22nd, th : 24th.
References enh::getOrdinalIndicator().
getStringDate() [1/2]
std::string enh::date::getStringDate () const inline
Get The date as a string.
Format : Day, ddth Month yyyy
eg : Tuesday, 12th May 2020
Overload
inline std::string getStringDate(std::string format) const;
References getDayOfWeekString(), getDaySuperScript(), and getMonthString().
getStringDate() [2/2]
std::string enh::date::getStringDate (std::string format) const inline
Get The date as a string in custom format.
Pass Argument as a string containing any of the following components.
Day : Name of day (Sunday) OR shDay : shortened name (Sun).
dd : The date (20) OR ddth : date with superscript (21st).
Month : The name of Month (January) OR mm : The numerical month (01 for January) OR shMonth : The name of month shortened (Jan).
yyyy : Year (2020).
Overload
inline std::string getStringDate() const;
Parameters
format : in : The format of date.
References getDayOfWeekString(), getDaySuperScript(), getMonthString(), getShortDayOfWeekString(), getShortMonthString(), and enh::signExtendValue().
setDate() [1/2]
void enh::date::setDate (time_t timeStamp) inline
Sets the date to the date indicated by argument.
Parameters
timeStamp : in : The time stamp which contains the date.
References enh::localtime(), and setDate().
setDate() [2/2]
void enh::date::setDate (unsigned short dy, unsigned short mnth, long yr, unsigned short week, unsigned ydy) inline
Sets the date to the date indicated by arguments.
Exception
Throws std::invalid_argument if dy, mnth, week, ydy is not within bounds. [0,month_limit], [0,11], [0,6], [0,year_limit) respectively.
Parameters
dy : in : The day of the month [1,month_limit].
mnth : in : The number of months after January [0,11].
yr : in : The Year.
week : in : The day of the week after Sunday [0,6].
ydy : in : The number of day after 01 January of that year [1,year_limit).
References enh::isConfined(), enh::month_limit(), and enh::year_limit().
The documentation for this class was generated from the following file:
F:/source/Enhance/src/Header/date.enh.h