Enhance: enh::timer< _per, time_unit > Class Template Reference
enh::timer< _per, time_unit > Class Template Reference
The class to create a timer that notifies all clients periodically.
#include <timer.enh.h>
Public Types
using unit = time_unit
The unit of measurement.
Public Member Functions
timer () noexcept
The constructor of the class.
~timer () noexcept
destructor of the class.
unsigned long long wait (unsigned long long expected) noexcept
The Functions blocks execution till the number of cycles elapsed is greater than or equal to the expected value.
unsigned long long wait () noexcept
The Functions blocks execution till the number of cycles elapsed is greater than or equal to the current elapsed cycles.
long long wait_for (unsigned mult_count, std::function< bool()> condition) noexcept
The function blocks for a certian cycles unless the condition becomes false.
void stop () noexcept
sets stopTimer to true.
void clear_stop () noexcept
sets stopTimer to false.
unsigned long long elapsed () noexcept
Returns the number of cycles elapsed from timer start.
unsigned long long wait_for (unsigned long mult_count) noexcept
blocks function execution for mult_count number of cycles.
bool isTimerCounting ()
Checks if timer is running.
bool start_timer () noexcept
The function to start timer.
bool operator! () noexcept
overloaded operator !, returns true if the timer Thread is not allocated.
void join () noexcept
Waits till timerThread finishes execution.
void force_join () noexcept
sets stopTimer flag to true, then waits for thread to join via enh::timer::join.
Static Public Member Functions
static time_pt program_start_point () noexcept
returns the start time_pt of the program.
static unit program_elapsed () noexcept
Returns the duration elapsed from program start in the type passed through the template.
Static Public Attributes
static constexpr unsigned period = _per
The period of timer.
Detailed Description
template<unsigned _per = 50U, class time_unit = std::chrono::milliseconds>
class enh::timer< _per, time_unit >
The class to create a timer that notifies all clients periodically.
The class will start a timer on instanciation and starts notifying all client threads, periodically.
The period is determined by the template arguments.
The period cannot be less than 5 if unit is milliseconds for accuracy.
The class cannot be instanciated using any other type than milliseconds, seconds, minutes and hours.
But the template can be instanciated with nanoseconds and microseconds, but object cannot be created.
hasErrorHandlers = false;
template
unsigned _per : The period of time between each notification.
unit : The unit of time of period.
Example
 #include <timer.enh.h>
 #include <iostream>
 int main()
 {
     enh::timer<1, std::chrono::seconds> test;
     for (int i = 0; i < 10; ++i)
     {
         test.wait();
         auto start = enh::high_res::now();
         test.wait_for(2);
         auto end = enh::high_res::now();
         std::chrono::milliseconds ms = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
         std::cout << "wait time : 2s, measured : " << ms.count() << "ms ; error : " << ms.count() - 2000 << "\n";
     }
     LOG_LINE;
     test.stop();
     LOG_LINE;
     enh::millis<10> test2;
     for (int i = 0; i < 10; ++i)
     {
         test2.wait();
         auto start = enh::high_res::now();
         test2.wait_for(5);
         auto end = enh::high_res::now();
         std::chrono::microseconds ms = std::chrono::duration_cast<std::chrono::microseconds>(end - start);
         std::cout << "wait time : 50ms, measured : " << ms.count() << "us ; error : " << ms.count() - 50000 << "\n";
     }
     test2.stop();
     return 0;
 }
 /* ****************************************************************************
 (measured time may vary)
 Output:
 wait time : 2s, measured : 2001ms ; error : 1
 wait time : 2s, measured : 2000ms ; error : 0
 wait time : 2s, measured : 2000ms ; error : 0
 wait time : 2s, measured : 2001ms ; error : 1
 wait time : 2s, measured : 2000ms ; error : 0
 wait time : 2s, measured : 1999ms ; error : -1
 wait time : 2s, measured : 2000ms ; error : 0
 wait time : 2s, measured : 1999ms ; error : -1
 wait time : 2s, measured : 2000ms ; error : 0
 wait time : 2s, measured : 2001ms ; error : 1
 wait time : 50ms, measured : 51022us ; error : 1022
 wait time : 50ms, measured : 49984us ; error : -16
 wait time : 50ms, measured : 49986us ; error : -14
 wait time : 50ms, measured : 50397us ; error : 397
 wait time : 50ms, measured : 50064us ; error : 64
 wait time : 50ms, measured : 49843us ; error : -157
 wait time : 50ms, measured : 50002us ; error : 2
 wait time : 50ms, measured : 49869us ; error : -131
 wait time : 50ms, measured : 49974us ; error : -26
 wait time : 50ms, measured : 49956us ; error : -44
 ******************************************************************************/
Constructor & Destructor Documentation
timer()
template<unsigned _per = 50U, class time_unit = std::chrono::milliseconds> enh::timer< _per, time_unit >::timer () inline noexcept
The constructor of the class.
The timer constructor also invokes enh::timer::start_timer.
Constructor fails assert if it is not a time type > ms.
References enh::timer< _per, time_unit >::clear_stop(), and enh::timer< _per, time_unit >::start_timer().
~timer()
template<unsigned _per = 50U, class time_unit = std::chrono::milliseconds> enh::timer< _per, time_unit >::~timer () inline noexcept
destructor of the class.
invokes enh::timer::join, waits till the timer Thread joins.
References enh::timer< _per, time_unit >::join().
Member Function Documentation
isTimerCounting()
template<unsigned _per = 50U, class time_unit = std::chrono::milliseconds> bool enh::timer< _per, time_unit >::isTimerCounting () inline
Checks if timer is running.
Return
If timer is running it returns true. Else it returns false;
join()
template<unsigned _per = 50U, class time_unit = std::chrono::milliseconds> void enh::timer< _per, time_unit >::join () inline noexcept
Waits till timerThread finishes execution.
The function blocks till the timer Thread joins.
If the timer Thread is empty, it returns immediately.
References enh::timer< _per, time_unit >::isTimerCounting().
start_timer()
template<unsigned _per = 50U, class time_unit = std::chrono::milliseconds> bool enh::timer< _per, time_unit >::start_timer () inline noexcept
The function to start timer.
The function clears the stopTimer flag, sets elapsed_cycles to 0 and then allocates a thread for the timer.
Return
Returns false if timer is already running.
References enh::timer< _per, time_unit >::clear_stop(), enh::timer< _per, time_unit >::isTimerCounting(), and O3_LIB_LOG_LINE.
wait() [1/2]
template<unsigned _per = 50U, class time_unit = std::chrono::milliseconds> unsigned long long enh::timer< _per, time_unit >::wait () inline noexcept
The Functions blocks execution till the number of cycles elapsed is greater than or equal to the current elapsed cycles.
1.
Return
The difference between elapsed cycles and expected (the "overshoot").
wait() [2/2]
template<unsigned _per = 50U, class time_unit = std::chrono::milliseconds> unsigned long long enh::timer< _per, time_unit >::wait (unsigned long long expected) inline noexcept
The Functions blocks execution till the number of cycles elapsed is greater than or equal to the expected value.
Invokes enh::timer::start_timer if timer is not active.
Return
The difference between elapsed cycles and expected (the "overshoot").
Parameters
expected : in : The expected cycle count to wait till.
References enh::timer< _per, time_unit >::start_timer().
wait_for() [1/2]
template<unsigned _per = 50U, class time_unit = std::chrono::milliseconds> unsigned long long enh::timer< _per, time_unit >::wait_for (unsigned long mult_count) inline noexcept
blocks function execution for mult_count number of cycles.
Returns the overshoot from the expected value.
Parameters
mult_count : in : The cycles to wait for.
References enh::timer< _per, time_unit >::wait().
wait_for() [2/2]
template<unsigned _per = 50U, class time_unit = std::chrono::milliseconds> long long enh::timer< _per, time_unit >::wait_for (unsigned mult_count, std::function< bool()> condition) inline noexcept
The function blocks for a certian cycles unless the condition becomes false.
The functions waits for a cycle then checks the condition passed through cond, and if it returns false, the function exits.
Return
-1 if the condition fails. The overshoot if it doesnt.
Parameters
mult_count : in : The amount of cycles to wait.
condition : in : The condition to exit immediately.
References enh::timer< _per, time_unit >::wait().
The documentation for this class was generated from the following file:
F:/source/Enhance/src/Header/timer.enh.h