Enhance: debug Namespace Reference
debug Namespace Reference
The namespace for diagnostics.
Functions
std::filesystem::path getFile (std::thread::id id, std::string function)
The file to get which file to log into.
void Log (std::string lg, std::string function)
Logs a string to a file indicated byt current thread.
void Log (std::string file, std::string function, unsigned long line)
Logs calling line, function and file to a file indicated by current thread.
void Log (std::string file, std::string function, unsigned long line, std::string descr)
Logs calling line, function, file and a description to a file indicated by current thread.
template<class T >
void Log (std::string file, std::string function, unsigned long line, std::string var, const T &val)
Logs calling line, function, file and a value to a file indicated by current thread.
Detailed Description
The namespace for diagnostics.
Function Documentation
getFile()
std::filesystem::path debug::getFile (std::thread::id id, std::string function)
The file to get which file to log into.
Return
The path of file.
Parameters
id : in : The calling thread id.
function : in : Logging function name.
Log() [1/4]
void debug::Log (std::string file, std::string function, unsigned long line)
Logs calling line, function and file to a file indicated by current thread.
Parameters
file : in : The file in which logging code is present.
function : in : Logging function name.
line : in : The line of file in which logging code is present.
References Log().
Log() [2/4]
void debug::Log (std::string file, std::string function, unsigned long line, std::string descr)
Logs calling line, function, file and a description to a file indicated by current thread.
Parameters
file : in : The file in which logging code is present.
function : in : Logging function name.
line : in : The line of file in which logging code is present.
descr : in : The string to log.
References Log().
Log() [3/4]
template<class T > void debug::Log (std::string file, std::string function, unsigned long line, std::string var, const T & val)
Logs calling line, function, file and a value to a file indicated by current thread.
The type should be accepted by the stream insertion operator.
Parameters
file : in : The file in which logging code is present.
function : in : Logging function name.
line : in : The line of file in which logging code is present.
var : in : The name of variable.
val : in : The value of the variable.
References Log().
Log() [4/4]
void debug::Log (std::string lg, std::string function)
Logs a string to a file indicated byt current thread.
The function which logs the string should be passed to function.
Parameters
lg : in : The string to log.
function : in : Logging function name.