Enhance C++ Libraries: enh::DateTime Class Reference
enh::DateTime Class Reference
Class for date and time joint manipulation.
#include <date_time.enh.h>
Public Member Functions
constexpr void set (unsigned short dy, unsigned short mnth, long yr, unsigned short week, unsigned short ydy, unsigned short sec, unsigned short min, unsigned short hr)
Sets the time and date to the time and date indicated by argument.
void set (time_t stamp)
Sets the time and date to the time and date indicated by argument.
void set ()
Sets the time and date to the current time and date.
constexpr DateTime (unsigned short dy, unsigned short mnth, long yr, unsigned short week, unsigned short ydy, unsigned short sec, unsigned short min, unsigned short hr)
Sets the time and date to the time and date indicated by argument.
DateTime (time_t stamp)
Sets the time and date to the time and date indicated by argument.
DateTime ()
Sets the time and date to the current time and date.
std::string getStringDateTime ()
Get The date and time as a string in default format.
std::string getStringDateTime (std::string format)
Get The date and time as a string in custom format.
constexpr void addHours (unsigned long long hr) noexcept
Adds to the hour part of time held.
constexpr void addMinutes (unsigned long long min) noexcept
Adds to the minute part of time held (also hour).
constexpr void addSeconds (unsigned long long sec) noexcept
Adds to the second part of time held (also hour).
constexpr void subHours (unsigned long long hr) noexcept
Reduce the hour part of time held.
constexpr void subMinutes (unsigned long long min) noexcept
Reduce the minute part of time held (also hour).
constexpr void subSeconds (unsigned long long sec) noexcept
Reduces the second part of time held (also hour).
constexpr bool isEqualTo (const DateTime &dt) const noexcept
Checks if argument is equal to this object.
constexpr bool isNotEqualTo (const DateTime &dt) const noexcept
Checks if argument is not equal to this object.
constexpr bool isLesserThan (const DateTime &dt) const noexcept
Checks if current DateTime is lesser than argument.
constexpr bool isLesserThanEq (const DateTime &dt) const noexcept
Checks if current DateTime is lesser than or equal to argument.
constexpr bool isGreaterThan (const DateTime &dt) const noexcept
Checks if current DateTime is greater than argument.
constexpr bool isGreaterThanEq (const DateTime &dt) const noexcept
Checks if current DateTime is greater than or equal to argument.
Public Member Functions inherited from enh::time_stamp
constexpr void setTime (unsigned short sec, unsigned short min, unsigned short hr)
Sets the time to the time indicated by arguments.
void setTime (time_t timeStamp)
Sets the time to the time indicated by argument.
void setTime ()
Sets the time to the current time.
constexpr time_stamp (unsigned short sec, unsigned short min, unsigned short hr)
Sets the time to the time indicated by arguments.
time_stamp (time_t timeStamp)
Sets the time to the time indicated by argument.
time_stamp ()
Sets the time to the current time.
constexpr unsigned long long addHours (unsigned long long hr) noexcept
Adds to the hour part of time held.
constexpr unsigned long long addMinutes (unsigned long long min) noexcept
Adds to the minute part of time held (also hour).
constexpr unsigned long long addSeconds (unsigned long long sec) noexcept
Adds to the second part of time held (also hour).
constexpr unsigned long long subHours (unsigned long long hr) noexcept
Reduce the hour part of time held.
constexpr unsigned long long subMinutes (unsigned long long min) noexcept
Reduce the minute part of time held (also hour).
constexpr unsigned long long subSeconds (unsigned long long sec) noexcept
Reduces the second part of time held (also hour).
constexpr unsigned short getSeconds () const noexcept
Get Seconds field.
constexpr unsigned short getMinutes () const noexcept
Get Minutes field.
constexpr unsigned short getHours () const noexcept
Get Hours field.
std::string getStringTime () const
Get The time as a string in default format.
std::string getStringTime (std::string format) const
Get The time as a string in custom format.
constexpr bool isEqualTo (const time_stamp &dt) const noexcept
Checks if argument is equal to this object.
constexpr bool isNotEqualTo (const time_stamp &dt) const noexcept
Checks if argument is not equal to this object.
constexpr bool isLesserThan (const time_stamp &dt) const noexcept
Checks if current time_stamp is lesser than argument.
constexpr bool isLesserThanEq (const time_stamp &dt) const noexcept
Checks if current time_stamp is lesser than or equal to argument.
constexpr bool isGreaterThan (const time_stamp &dt) const noexcept
Checks if current time_stamp is greater than argument.
constexpr bool isGreaterThanEq (const time_stamp &dt) const noexcept
Checks if current time_stamp is greater than or equal to argument.
Detailed Description
Class for date and time joint manipulation.
Examples
 #include <date_time.enh.h>
 #include <iostream>
 int main()
 {
     enh::DateTime dt[] = {
         {}, {}, {}, {std::time(nullptr)}, {
             22,6,2020,0,300,25,16,21
         }
     };
     dt[0].addHours(25);
     dt[1].addDay(200);
     dt[2].addDay(50);
     dt[2].addMinutes(360);
     for (auto i : dt)
     {
         std::cout << i.getHours() << " " << i.getMinutes() << " " << i.getSeconds() << "\n";
         std::cout << i.getDayOfWeek() << " " << i.getDayOfWeekString() << " " << i.getShortDayOfWeekString()
             << " " << i.getDayOfMonth() << " " << i.getMonth() << " " << i.getMonthString()
             << " " << i.getShortMonthString() << " " << i.getDayOfYear() << "\n\n";
         std::cout << "def : " << i.getStringDateTime() << "\n\n";
         std::string form[] = {
             "sec:min:hour; Day, ddth - Month - yyyy",
             "sec of the minth minute of the hourth hour in the day of Day which is ddth of Month of yyyy",
             "sec/min/hour/shDay/dd/shMonth/yyyy",
             "hour : shDay, dd mm yyyy"
         };
         for (auto j : form)
             std::cout << "format :  " << j << " \n>> " << i.getStringDateTime(j) << "\n";
         std::cout << "\n";
     }
     return 0;
 }
 /* ****************************************************************************
 Output :
 20 38 12
 1 Monday Mon 18 4 May May 167
 def : 20 : 38 : 12 ; Monday, 18th May 2020
 format :  sec:min:hour; Day, ddth - Month - yyyy
 >> 12:38:20; Monday, 18th - May - 2020
 format :  sec of the minth minute of the hourth hour in the day of Day which is ddth of Month of yyyy
 >> 12 of the 38th minute of the 20th hour in the day of Monday which is 18th of May of 2020
 format :  sec/min/hour/shDay/dd/shMonth/yyyy
 >> 12/38/20/Mon/18/May/2020
 format :  hour : shDay, dd mm yyyy
 >> 20 : Mon, 18 05 2020
 18 38 12
 2 Tuesday Tue 9 11 December Dec 344
 def : 18 : 38 : 12 ; Tuesday, 9th December 2020
 format :  sec:min:hour; Day, ddth - Month - yyyy
 >> 12:38:18; Tuesday, 09th - December - 2020
 format :  sec of the minth minute of the hourth hour in the day of Day which is ddth of Month of yyyy
 >> 12 of the 38th minute of the 18th hour in the day of Tuesday which is 09th of December of 2020
 format :  sec/min/hour/shDay/dd/shMonth/yyyy
 >> 12/38/18/Tue/09/Dec/2020
 format :  hour : shDay, dd mm yyyy
 >> 18 : Tue, 09 12 2020
 0 44 12
 3 Wednesday Wed 8 6 July Jul 226
 def : 00 : 44 : 12 ; Wednesday, 8th July 2020
 format :  sec:min:hour; Day, ddth - Month - yyyy
 >> 12:44:00; Wednesday, 08th - July - 2020
 format :  sec of the minth minute of the hourth hour in the day of Day which is ddth of Month of yyyy
 >> 12 of the 44th minute of the 00th hour in the day of Wednesday which is 08th of July of 2020
 format :  sec/min/hour/shDay/dd/shMonth/yyyy
 >> 12/44/00/Wed/08/Jul/2020
 format :  hour : shDay, dd mm yyyy
 >> 00 : Wed, 08 07 2020
 18 38 12
 0 Sunday Sun 17 4 May May 137
 def : 18 : 38 : 12 ; Sunday, 17th May 2020
 format :  sec:min:hour; Day, ddth - Month - yyyy
 >> 12:38:18; Sunday, 17th - May - 2020
 format :  sec of the minth minute of the hourth hour in the day of Day which is ddth of Month of yyyy
 >> 12 of the 38th minute of the 18th hour in the day of Sunday which is 17th of May of 2020
 format :  sec/min/hour/shDay/dd/shMonth/yyyy
 >> 12/38/18/Sun/17/May/2020
 format :  hour : shDay, dd mm yyyy
 >> 18 : Sun, 17 05 2020
 21 16 25
 0 Sunday Sun 22 6 July Jul 300
 def : 21 : 16 : 25 ; Sunday, 22nd July 2020
 format :  sec:min:hour; Day, ddth - Month - yyyy
 >> 25:16:21; Sunday, 22nd - July - 2020
 format :  sec of the minth minute of the hourth hour in the day of Day which is ddth of Month of yyyy
 >> 25 of the 16th minute of the 21th hour in the day of Sunday which is 22nd of July of 2020
 format :  sec/min/hour/shDay/dd/shMonth/yyyy
 >> 25/16/21/Sun/22/Jul/2020
 format :  hour : shDay, dd mm yyyy
 >> 21 : Sun, 22 07 2020
 ******************************************************************************/
Constructor & Destructor Documentation
DateTime() [1/2]
constexpr enh::DateTime::DateTime (unsigned short dy, unsigned short mnth, long yr, unsigned short week, unsigned short ydy, unsigned short sec, unsigned short min, unsigned short hr) inline constexpr
Sets the time and date to the time and date indicated by argument.
Parameters
dy : in : The day of the month [1,month_limit].
mnth : in : The number of months after January [0,11].
yr : in : The Year.
week : in : The day of the week after Sunday [0,6].
ydy : in : The number of day after 01 January of that year [1,year_limit).
sec : in : The seconds field [0,60].
min : in : The minutes field [0,59].
hr : in : The hours field [0,59].
DateTime() [2/2]
enh::DateTime::DateTime (time_t stamp) inline
Sets the time and date to the time and date indicated by argument.
Parameters
stamp : in : The time stamp which contains the date and time.
References set().
Member Function Documentation
addHours()
constexpr void enh::DateTime::addHours (unsigned long long hr) inline constexpr noexcept
Adds to the hour part of time held.
Parameters
hr : in : The hours to add.
References enh::time_stamp::addHours().
addMinutes()
constexpr void enh::DateTime::addMinutes (unsigned long long min) inline constexpr noexcept
Adds to the minute part of time held (also hour).
Parameters
min : in : The minutes to add.
References enh::time_stamp::addMinutes(), and enh::min().
addSeconds()
constexpr void enh::DateTime::addSeconds (unsigned long long sec) inline constexpr noexcept
Adds to the second part of time held (also hour).
Parameters
sec : in : The seconds to add.
References enh::time_stamp::addSeconds().
getStringDateTime() [1/2]
std::string enh::DateTime::getStringDateTime () inline
Get The date and time as a string in default format.
hour:min:sec ; Day, ddth Month yyyy
Overload
inline std::string getStringDateTime(std::string format) const;
References enh::time_stamp::getStringTime().
getStringDateTime() [2/2]
std::string enh::DateTime::getStringDateTime (std::string format) inline
Get The date and time as a string in custom format.
Pass Argument as a string containing any of the following components.
Day : Name of day (Sunday) OR shDay : shortened name (Sun).
dd : The date (20) OR ddth : date with superscript (21st).
Month : The name of Month (January) OR mm : The numerical month (01 for January) OR shMonth : The name of month shortened (Jan).
yyyy : Year (2020).
sec : The seconds.
min : The minutes.
hour : The hours.
Overload
inline std::string getStringDateTime() const;
Parameters
format : in : The format of date.
References enh::time_stamp::getStringTime().
isEqualTo()
constexpr bool enh::DateTime::isEqualTo (const DateTime & dt) const inline constexpr noexcept
Checks if argument is equal to this object.
Return
Returns true if year, month and day of argument is equal to current object.
Parameters
dt : in : The DateTime to compare with.
References enh::time_stamp::isEqualTo().
isGreaterThan()
constexpr bool enh::DateTime::isGreaterThan (const DateTime & dt) const inline constexpr noexcept
Checks if current DateTime is greater than argument.
Return
Returns true if current DateTime is greater than argument.
Parameters
dt : in : The DateTime to compare with.
References isLesserThanEq().
isGreaterThanEq()
constexpr bool enh::DateTime::isGreaterThanEq (const DateTime & dt) const inline constexpr noexcept
Checks if current DateTime is greater than or equal to argument.
Return
Returns true if current DateTime is greater than or equal to argument.
Parameters
dt : in : The DateTime to compare with.
References isLesserThan().
isLesserThan()
constexpr bool enh::DateTime::isLesserThan (const DateTime & dt) const inline constexpr noexcept
Checks if current DateTime is lesser than argument.
Return
Returns true if current DateTime is lesser than argument.
Parameters
dt : in : The DateTime to compare with.
References enh::time_stamp::isLesserThan().
isLesserThanEq()
constexpr bool enh::DateTime::isLesserThanEq (const DateTime & dt) const inline constexpr noexcept
Checks if current DateTime is lesser than or equal to argument.
Return
Returns true if current DateTime is lesser than or equal to argument.
Parameters
dt : in : The DateTime to compare with.
References enh::time_stamp::isLesserThanEq().
isNotEqualTo()
constexpr bool enh::DateTime::isNotEqualTo (const DateTime & dt) const inline constexpr noexcept
Checks if argument is not equal to this object.
Return
Returns true if year, month and day of argument is not equal to current object.
Parameters
dt : in : The DateTime to compare with.
References isEqualTo().
set() [1/2]
void enh::DateTime::set (time_t stamp) inline
Sets the time and date to the time and date indicated by argument.
Parameters
stamp : in : The time stamp which contains the date and time.
References enh::localtime(), and set().
set() [2/2]
constexpr void enh::DateTime::set (unsigned short dy, unsigned short mnth, long yr, unsigned short week, unsigned short ydy, unsigned short sec, unsigned short min, unsigned short hr) inline constexpr
Sets the time and date to the time and date indicated by argument.
Parameters
dy : in : The day of the month [1,month_limit].
mnth : in : The number of months after January [0,11].
yr : in : The Year.
week : in : The day of the week after Sunday [0,6].
ydy : in : The number of day after 01 January of that year [1,year_limit).
sec : in : The seconds field [0,60].
min : in : The minutes field [0,59].
hr : in : The hours field [0,59].
References enh::min(), and enh::time_stamp::setTime().
subHours()
constexpr void enh::DateTime::subHours (unsigned long long hr) inline constexpr noexcept
Reduce the hour part of time held.
Parameters
hr : in : The hours to reduce.
References enh::time_stamp::subHours().
subMinutes()
constexpr void enh::DateTime::subMinutes (unsigned long long min) inline constexpr noexcept
Reduce the minute part of time held (also hour).
Parameters
min : in : The minutes to reduce.
References enh::min(), and enh::time_stamp::subMinutes().
subSeconds()
constexpr void enh::DateTime::subSeconds (unsigned long long sec) inline constexpr noexcept
Reduces the second part of time held (also hour).
Parameters
sec : in : The seconds to reduce.
References enh::time_stamp::subSeconds().
The documentation for this class was generated from the following file:
F:/source/Enhance/src/Header/date_time.enh.h