Enhance: enh::counter Class Reference
enh::counter Class Reference
The class for counter functionality.
#include <counter.enh.h>
Public Member Functions
~counter ()
The destructor for the class.
counter () noexcept
The constructor of the class sets all to 0.
counter (const counter &c) noexcept
default copy constructor.
counter (counter &&c) noexcept
default move constructor.
counter (unsigned sec, unsigned min, unsigned hr, unsigned long long dy) noexcept
constructs using these values.
counter & operator= (const counter &c) noexcept
default copy assignment.
counter & operator= (counter &&c) noexcept
default copy assignment.
counter & reset () noexcept
Resets state to 0s 0m 0hr 0day.
counter & operator() () noexcept
Resets state to 0s 0m 0hr 0day.
void set_seconds (unsigned long long sec) noexcept
Functon sets the value of state to sec number of seconds.
void add_seconds (unsigned long long sec) noexcept
Functon adds sec seconds to the value of state.
void set_minutes (unsigned long long min) noexcept
Functon sets the value of state to min number of minutes.
void add_minutes (unsigned long long min) noexcept
Functon adds min minutes to the value of state.
void set_hours (unsigned long long hr) noexcept
Functon sets the value of state to hr number of hours.
void add_hours (unsigned long long hr) noexcept
Functon adds hr hours to the value of state.
void set_days (unsigned long long dy) noexcept
Functon sets the value of state to dy number of days.
void add_days (unsigned long long dy) noexcept
Functon adds dy days to the value of state.
unsigned get_seconds () const noexcept
Returns the seconds part of the state.
unsigned get_minutes () const noexcept
Returns the minutes part of the state.
unsigned get_hours () const noexcept
Returns the hours part of the state.
unsigned long long get_days () const noexcept
Returns the days part of the state.
unsigned long long get_total_hours () const noexcept
Returns the total hours elapsed.
void set (unsigned sec, unsigned min, unsigned hr, unsigned long long dy) noexcept
Functon sets the value of state to state input.
void add (unsigned sec, unsigned min, unsigned hr, unsigned long long dy)
Functon adds inputs to the state.
std::string get_string () const
Returns the information as a string.
void read_raw (const char *raw, unsigned size)
read raw data from argument to each field.
std::string get_raw () const
get string holding raw data stream representation of the objects state.
bool operator< (counter a) const noexcept
Checks if current object is at lower time count than parameter.
bool operator> (counter a) const noexcept
Checks if current object is at greater time count than parameter.
bool operator== (counter a) const noexcept
Checks if current object is at equal time count than parameter.
bool operator<= (counter a) const noexcept
Checks if current object is at lower or equal time count than parameter.
bool operator>= (counter a) const noexcept
Checks if current object is at greater or equal time count than parameter.
Static Public Member Functions
static constexpr unsigned get_seconds_size ()
get size of seconds storage type
static constexpr unsigned get_minutes_size ()
get size of minutes storage type
static constexpr unsigned get_hours_size ()
get size of hours storage type
static constexpr unsigned get_days_size ()
get size of days storage type
static constexpr unsigned get_raw_size ()
get size of raw data stream representing this.
Detailed Description
The class for counter functionality.
hasErrorHandlers = false;
Make sure to compile counter.cpp also.
Example
 #include <counter.enh.h>
 #include <iostream>
 int main()
 {
     enh::counter ct;                        // 0s 0m 0h 0d
     enh::counter state(25, 15, 12, 365);    // 25s 15m 12h 365d
     std::cout << ct.get_seconds() << " " << ct.get_minutes() << " "
         << ct.get_hours() << " " << ct.get_days() << " "
         << ct.get_total_hours() << "\n";
     std::cout << state.get_seconds() << " " << state.get_minutes() << " "
         << state.get_hours() << " " << state.get_days() << " "
         << state.get_total_hours() << "\n";
     std::cout << enh::counter(2, 3, 4, 256) << "\n";
     std::cout << enh::counter(2, 25, 6, 251).get_string() << "\n";
     return 0;
 }
 /* ****************************************************************************
 Output:
 0 0 0 0 0
 25 15 12 365 8772
 2s : 3min : 4hr : 256days ; 6148 total hours
 2s : 25min : 6hr : 251days ; 6030 total hours
 ******************************************************************************/
Constructor & Destructor Documentation
counter()
enh::counter::counter (unsigned sec, unsigned min, unsigned hr, unsigned long long dy) inline noexcept
constructs using these values.
Setting of the state is done by ignoring the excess (sec < 60, min < 60, hr < 24).
Parameters
sec : in : The seconds to be set.
min : in : The minutes to be set.
hr : in : The hours to be set.
dy : in : The days to be set.
References enh::min(), and set().
Member Function Documentation
add()
void enh::counter::add (unsigned sec, unsigned min, unsigned hr, unsigned long long dy) inline
Functon adds inputs to the state.
Parameters
sec : in : The seconds to be added.
min : in : The minutes to be added.
hr : in : The hours to be added.
dy : in : The days to be added.
References add_days(), add_hours(), add_minutes(), add_seconds(), and enh::min().
add_days()
void enh::counter::add_days (unsigned long long dy) inline noexcept
Functon adds dy days to the value of state.
Parameters
dy : in : The days to be added.
add_hours()
void enh::counter::add_hours (unsigned long long hr) inline noexcept
Functon adds hr hours to the value of state.
If hr + hours is more than 24, value is added to days also.
Parameters
hr : in : The hours to be added.
References add_days().
add_minutes()
void enh::counter::add_minutes (unsigned long long min) inline noexcept
Functon adds min minutes to the value of state.
If min + minutes is more than 60, value is added to hours, days also.
Parameters
min : in : The minutes to be added.
References add_hours(), and enh::min().
add_seconds()
void enh::counter::add_seconds (unsigned long long sec) inline noexcept
Functon adds sec seconds to the value of state.
If sec + seconds is more than 60, value is added to minutes, hours, days also.
Parameters
sec : in : The seconds to be added.
References add_minutes().
get_days()
unsigned long long enh::counter::get_days () const inline noexcept
Returns the days part of the state.
Return
The number of days.
get_hours()
unsigned enh::counter::get_hours () const inline noexcept
Returns the hours part of the state.
Return
The number of hours.
get_minutes()
unsigned enh::counter::get_minutes () const inline noexcept
Returns the minutes part of the state.
Return
The number of minutes.
get_seconds()
unsigned enh::counter::get_seconds () const inline noexcept
Returns the seconds part of the state.
Return
The number of seconds.
get_string()
std::string enh::counter::get_string () const inline
Returns the information as a string.
Return
The info formatted as a string.
References get_days(), get_hours(), get_minutes(), get_seconds(), and get_total_hours().
get_total_hours()
unsigned long long enh::counter::get_total_hours () const inline noexcept
Returns the total hours elapsed.
Return
The total hours elapsed.
operator()()
counter& enh::counter::operator() () inline noexcept
Resets state to 0s 0m 0hr 0day.
Return
Reference to current state.
References reset().
operator<()
bool enh::counter::operator< (counter a) const inline noexcept
Checks if current object is at lower time count than parameter.
Return
Returns true if current state is less than parameter.
Parameters
a : in : The argument to check against.
operator<=()
bool enh::counter::operator<= (counter a) const inline noexcept
Checks if current object is at lower or equal time count than parameter.
Return
Returns true if current state is less than or equal parameter.
Parameters
a : in : The argument to check against.
operator==()
bool enh::counter::operator== (counter a) const inline noexcept
Checks if current object is at equal time count than parameter.
Return
Returns true if current state is equal to parameter.
Parameters
a : in : The argument to check against.
operator>()
bool enh::counter::operator> (counter a) const inline noexcept
Checks if current object is at greater time count than parameter.
Return
Returns true if current state is greater than parameter.
Parameters
a : in : The argument to check against.
operator>=()
bool enh::counter::operator>= (counter a) const inline noexcept
Checks if current object is at greater or equal time count than parameter.
Return
Returns true if current state is more than or equal parameter.
Parameters
a : in : The argument to check against.
read_raw()
void enh::counter::read_raw (const char * raw, unsigned size) inline
read raw data from argument to each field.
Parameters
raw : in : The raw data stream.
size : in : The length of the raw stream. (should be get_raw_size()).
References get_hours_size(), get_minutes_size(), get_raw_size(), and get_seconds_size().
reset()
counter& enh::counter::reset () inline noexcept
Resets state to 0s 0m 0hr 0day.
Return
Reference to current state.
set()
void enh::counter::set (unsigned sec, unsigned min, unsigned hr, unsigned long long dy) inline noexcept
Functon sets the value of state to state input.
Setting of the state is done by ignoring the excess (sec < 60, min < 60, hr < 24).
Parameters
sec : in : The seconds to be set.
min : in : The minutes to be set.
hr : in : The hours to be set.
dy : in : The days to be set.
References enh::min().
set_days()
void enh::counter::set_days (unsigned long long dy) inline noexcept
Functon sets the value of state to dy number of days.
Parameters
dy : in : The days to be set.
References reset().
set_hours()
void enh::counter::set_hours (unsigned long long hr) inline noexcept
Functon sets the value of state to hr number of hours.
Reset is called. If hr is more than 60, It is converted to hr, day format and overwritten over old values.
Parameters
hr : in : The hours to be set.
References add_days(), and reset().
set_minutes()
void enh::counter::set_minutes (unsigned long long min) inline noexcept
Functon sets the value of state to min number of minutes.
Reset is called. If min is more than 60, It is converted to min, hr, day format and overwritten over old values.
Parameters
min : in : The minutes to be set.
References add_hours(), enh::min(), and reset().
set_seconds()
void enh::counter::set_seconds (unsigned long long sec) inline noexcept
Functon sets the value of state to sec number of seconds.
Reset is called. If sec is more than 60, It is converted to sec, min, hr, day format and overwritten over old values.
Parameters
sec : in : The seconds to be set.
References add_minutes(), and reset().
The documentation for this class was generated from the following file:
F:/source/Enhance/src/Header/counter.enh.h